;
; File generated by cc65 v 2.17 - Git 535088fe
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088fe"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_port_write
	.export		_port_set
	.export		_port_clr
	.export		_port_tgl

.segment	"DATA"

_port_cache:
	.byte	$00

; ---------------------------------------------------------------
; void __near__ port_write (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_port_write: near

.segment	"CODE"

	jsr     pusha
	lda     (sp)
	sta     _port_cache
	sta     $7C00
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ port_set (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_port_set: near

.segment	"CODE"

	jsr     pusha
	lda     (sp)
	ora     _port_cache
	sta     _port_cache
	sta     $7C00
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ port_clr (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_port_clr: near

.segment	"CODE"

	jsr     pusha
	lda     (sp)
	eor     #$FF
	and     _port_cache
	sta     _port_cache
	sta     $7C00
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ port_tgl (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_port_tgl: near

.segment	"CODE"

	jsr     pusha
	lda     (sp)
	eor     _port_cache
	sta     _port_cache
	sta     $7C00
	jmp     incsp1

.endproc

