;
; File generated by cc65 v 2.17 - Git 535088fe
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088fe"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_hd44780_init
	.import		_delay_ms
	.import		_port_write
	.import		_port_tgl
	.export		_main

.segment	"BSS"

_buffer:
	.res	64,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$80
	jsr     _port_write
	jsr     _hd44780_init
	cli
L000A:	lda     #$85
	jsr     _port_tgl
	lda     #$FA
	jsr     _delay_ms
	bra     L000A

.endproc

