;
; File generated by cc65 v 2.18 - Git b525554b
;
	.fopt		compiler,"cc65 v 2.18 - Git b525554b"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_strchr
	.import		_strtok
	.import		_strcasecmp
	.export		_parse_cmd
	.import		_mos6551_puts
	.export		_komendy

.segment	"RODATA"

_komendy:
	.byte	$74,$65,$73,$74,$00
	.res	7,$00
	.addr	_test_service
S0004:
	.byte	$49,$6E,$76,$61,$6C,$69,$64,$20,$6F,$72,$20,$6D,$69,$73,$73,$69
	.byte	$6E,$67,$20,$70,$61,$72,$61,$6D,$65,$74,$65,$72,$0D,$0A,$00
S0007	:=	S0004+0
S0006:
	.byte	$55,$6E,$6B,$6E,$6F,$77,$6E,$20,$63,$6F,$6D,$6D,$61,$6E,$64,$0D
	.byte	$0A,$00
S0009	:=	S0006+0
S000A:
	.byte	$54,$65,$73,$74,$0D,$0A,$00
S0005:
	.byte	$4F,$4B,$0D,$0A,$00
S0008	:=	S0005+0
S0002:
	.byte	$20,$00,$00
S0003:
	.byte	$20,$00

; ---------------------------------------------------------------
; void __near__ parse_cmd (char *pBuf)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_parse_cmd: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp3
	ldy     #$06
	jsr     pushwysp
	ldx     #$00
	lda     #$20
	jsr     _strchr
	stx     tmp1
	ora     tmp1
	jeq     L0018
	ldy     #$06
	jsr     pushwysp
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _strtok
	ldy     #$01
	jsr     staxysp
	lda     #$00
L0017:	sta     (sp)
	lda     (sp)
	jne     L0004
	jsr     push0
	ldy     #$06
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	jsr     _strcasecmp
	jsr     tosicmp
	bne     L0005
	jsr     push0
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     _strtok
	ldy     #$01
	jsr     staxysp
	jsr     push0
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	ldy     #$0D
	jsr     pushwidx
	ldy     #$06
	jsr     ldaxysp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	jsr     tosicmp
	bne     L0008
	lda     #<(S0004)
	ldx     #>(S0004)
	jmp     L0012
L0008:	lda     #<(S0005)
	ldx     #>(S0005)
	jmp     L0012
L0005:	lda     (sp)
	ina
	jmp     L0017
L0004:	lda     #<(S0006)
	ldx     #>(S0006)
	bra     L0012
L0018:	sta     (sp)
	lda     (sp)
	bne     L000C
	jsr     push0
	ldy     #$08
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	jsr     _strcasecmp
	jsr     tosicmp
	bne     L000D
	jsr     push0
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	ldy     #$0D
	jsr     pushwidx
	ldx     #$00
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	jsr     tosicmp
	bne     L0010
	lda     #<(S0007)
	ldx     #>(S0007)
	bra     L0012
L0010:	lda     #<(S0008)
	ldx     #>(S0008)
	bra     L0012
L000D:	lda     (sp)
	ina
	bra     L0018
L000C:	lda     #<(S0009)
	ldx     #>(S0009)
L0012:	jsr     _mos6551_puts
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ test_service (char *params)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_service: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp6
	lda     #<(S000A)
	ldx     #>(S000A)
	jsr     _mos6551_puts
	ldx     #$00
	lda     #$01
	jmp     incsp8

.endproc

